version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: my-mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=parth

  mongo-express:
    image: mongo-express
    container_name: express-db
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=parth
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb